# Form implementation generated from reading ui file 'Remind_main.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(579, 540)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Icons for app Birthday reminder/birth.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color: #1E1E1E;\n"
"}\n"
"QPushButton{\n"
"    background-color: black;\n"
"    color: yellow;\n"
"    border: 1px solid #483D8B;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #2F4F4F;\n"
"    color: #FF0000;\n"
"    border: 1px dashed #000080;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px dashed #00FA9A;\n"
"    color: #00FA9A;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: black;\n"
"    color: #800000;\n"
"    border: none;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: #DCDCDC;\n"
"    color:     #000080;\n"
"    border: 1px solid yellow; \n"
"}\n"
"QLineEdit:focus{\n"
"    border: 3px dashed #800000;\n"
"}\n"
"QLabel{\n"
"    color: #FF4500;\n"
"}\n"
"QGroupBox{\n"
"    backgrond-color: #696969;\n"
"    color: #7FFF00;\n"
"    border: 1px solid #0000CD;\n"
"}\n"
"QRadioButton{\n"
"    color: #FF4500;\n"
"}\n"
"QRadioButton:hover{\n"
"    color: #00FF00;\n"
"}\n"
"\n"
"QCalendarWidget QWidget{\n"
"    alternate-background-color: #008B8B;    \n"
"}\n"
"QCalendarWidget QAbstractItemView:enabled{\n"
"    background-color: #000;\n"
"    color: #FFD700;\n"
"    border: 1px solid #8A2BE2;\n"
"    selection-background-color: #2F4F4F;\n"
"    selection-color: rgb(0, 255, 0);\n"
"}\n"
"\n"
"#qt_calendar_navigationbar{\n"
"    background-color: #2F4F4F;\n"
"    border: 1px solid #8A2BE2;\n"
"} \n"
"#qt_calendar_prevmonth,\n"
"#qt_calendar_nextmonth{\n"
"    border: none;\n"
"    qproperty-icon: none;\n"
"    min-width: 13px;\n"
"    max-width: 13px;\n"
"    min-height: 13px;\n"
"    max-height: 13px;\n"
"    background-color: transparent;\n"
"    padding: 5px;\n"
"    color: #00FF00;\n"
"}\n"
"#qt_calendar_prevmonth{\n"
"    matgin-left: 5px;\n"
"    qproperty-text: \"<\";\n"
"}\n"
"#qt_calendar_nextmonth{\n"
"    matgin-right: 5px;\n"
"    qproperty-text: \">\";\n"
"}\n"
"#qt_calendar_prevmonth:hover,\n"
"#qt_calendar_nextmonth:hover{\n"
"    border: 1px dashed #00FA9A;\n"
"    color: #00FA9A;\n"
"    background-color: #000;\n"
"}\n"
"#qt_calendar_prevmonth:pressed,\n"
"#qt_calendar_nextmonth:pressed{\n"
"    border: 1px dashed #00FA9A;\n"
"    color: #00FA9A;\n"
"    background-color: #000;\n"
"}\n"
"#qt_calendar_yearbutton{\n"
"    background-color: #2F4F4F;\n"
"    color: #00FA9A;\n"
"    margin: 5px;\n"
"    border_radius: 5px;\n"
"    font-size: 13px;\n"
"    padding: 5px 6px;\n"
"}\n"
"#qt_calendar_monthbutton{\n"
"    background-color: #2F4F4F;\n"
"    color: #00FA9A;\n"
"    width: 110px;\n"
"    margin: 4px;\n"
"    border_radius: 5px;\n"
"    font-size: 13px;\n"
"    padding: 5 px 8px;\n"
"}\n"
"#qt_calendar_yearbutton:hover,\n"
"#qt_calendar_monthbutton:hover{\n"
"    border: 2px dashed #00FA9A;\n"
"    color: #00FA9A;\n"
"    background-color: #000;    \n"
"}\n"
"#qt_calendar_yearbutton:pressed,\n"
"#qt_calendar_monthbutton:pressed{\n"
"    border: 2px dashed #00FA9A;\n"
"    color: #00FA9A;\n"
"    background-color: #000;    \n"
"}\n"
"QCalendarWidget QToolButton QMenu{\n"
"    backgrond-color: #2F4F4F;\n"
"    color: yellow;\n"
"}\n"
"QCalendarWidget QToolButton QMenu:item{\n"
"    border: 1px solid red;\n"
"    padding: 5px;\n"
"}\n"
"QCalendarWidget QToolButton QMenu:item:selected{\n"
"    border: 1px dashed #00FA9A;\n"
"    color: #00FA9A;\n"
"}\n"
"\n"
"QListWidget{\n"
"    border : 1px solid #8A2BE2;\n"
"    background : #696969;\n"
"}\n"
"QListView::item{\n"
"    border : 1px solid #FF7F50;\n"
"    color: yellow;\n"
"    background : #00008B;\n"
"    padding: 5px;\n"
"    font-size: 13px;\n"
"}")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Ukrainian, QtCore.QLocale.Country.Ukraine))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 10, 312, 211))
        self.calendarWidget.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.calendarWidget.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Ukrainian, QtCore.QLocale.Country.Ukraine))
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setSelectionMode(QtWidgets.QCalendarWidget.SelectionMode.SingleSelection)
        self.calendarWidget.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.HorizontalHeaderFormat.ShortDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.VerticalHeaderFormat.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(330, 10, 220, 131))
        self.groupBox.setObjectName("groupBox")
        self.line_path = QtWidgets.QLineEdit(self.groupBox)
        self.line_path.setGeometry(QtCore.QRect(10, 20, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_path.setFont(font)
        self.line_path.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.line_path.setClearButtonEnabled(False)
        self.line_path.setObjectName("line_path")
        self.pushButton_clear = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_clear.setEnabled(True)
        self.pushButton_clear.setGeometry(QtCore.QRect(8, 96, 61, 31))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_path_file = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_path_file.setGeometry(QtCore.QRect(186, 20, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_path_file.setFont(font)
        self.pushButton_path_file.setStyleSheet("")
        self.pushButton_path_file.setObjectName("pushButton_path_file")
        self.pushButton_FAQ_path = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_FAQ_path.setGeometry(QtCore.QRect(185, 55, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_FAQ_path.setFont(font)
        self.pushButton_FAQ_path.setStyleSheet("")
        self.pushButton_FAQ_path.setObjectName("pushButton_FAQ_path")
        self.label_exists_file = QtWidgets.QLabel(self.groupBox)
        self.label_exists_file.setGeometry(QtCore.QRect(12, 65, 166, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_exists_file.setFont(font)
        self.label_exists_file.setText("")
        self.label_exists_file.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_exists_file.setWordWrap(True)
        self.label_exists_file.setObjectName("label_exists_file")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 230, 131, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_create_file = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_create_file.setGeometry(QtCore.QRect(10, 20, 111, 31))
        self.pushButton_create_file.setObjectName("pushButton_create_file")
        self.pushButton_update_file = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_update_file.setEnabled(True)
        self.pushButton_update_file.setGeometry(QtCore.QRect(10, 60, 111, 31))
        self.pushButton_update_file.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.pushButton_update_file.setObjectName("pushButton_update_file")
        self.label_info_birth_now = QtWidgets.QLabel(self.centralwidget)
        self.label_info_birth_now.setGeometry(QtCore.QRect(333, 276, 239, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_info_birth_now.setFont(font)
        self.label_info_birth_now.setStyleSheet("color: #FFD700;")
        self.label_info_birth_now.setText("")
        self.label_info_birth_now.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_info_birth_now.setWordWrap(True)
        self.label_info_birth_now.setObjectName("label_info_birth_now")
        self.listWidget_birth_now = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_birth_now.setGeometry(QtCore.QRect(332, 316, 241, 61))
        self.listWidget_birth_now.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.listWidget_birth_now.setMidLineWidth(1)
        self.listWidget_birth_now.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.listWidget_birth_now.setProperty("showDropIndicator", False)
        self.listWidget_birth_now.setAlternatingRowColors(False)
        self.listWidget_birth_now.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.listWidget_birth_now.setFlow(QtWidgets.QListView.Flow.TopToBottom)
        self.listWidget_birth_now.setProperty("isWrapping", False)
        self.listWidget_birth_now.setLayoutMode(QtWidgets.QListView.LayoutMode.SinglePass)
        self.listWidget_birth_now.setViewMode(QtWidgets.QListView.ViewMode.ListMode)
        self.listWidget_birth_now.setWordWrap(True)
        self.listWidget_birth_now.setObjectName("listWidget_birth_now")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(150, 230, 171, 121))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(10, 20, 144, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color: yellow;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_timer = QtWidgets.QLabel(self.groupBox_3)
        self.label_timer.setGeometry(QtCore.QRect(10, 48, 144, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_timer.setFont(font)
        self.label_timer.setStyleSheet("color: yellow; ")
        self.label_timer.setText("")
        self.label_timer.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_timer.setObjectName("label_timer")
        self.pushButton_stop_timer = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_stop_timer.setGeometry(QtCore.QRect(20, 80, 121, 36))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_stop_timer.setFont(font)
        self.pushButton_stop_timer.setObjectName("pushButton_stop_timer")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setEnabled(True)
        self.pushButton_exit.setGeometry(QtCore.QRect(514, 501, 61, 31))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_setting = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_setting.setEnabled(True)
        self.pushButton_setting.setGeometry(QtCore.QRect(418, 501, 88, 31))
        self.pushButton_setting.setObjectName("pushButton_setting")
        self.listWidget_birth_last = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_birth_last.setGeometry(QtCore.QRect(332, 204, 241, 61))
        self.listWidget_birth_last.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.listWidget_birth_last.setMidLineWidth(1)
        self.listWidget_birth_last.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.listWidget_birth_last.setProperty("showDropIndicator", False)
        self.listWidget_birth_last.setAlternatingRowColors(False)
        self.listWidget_birth_last.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.listWidget_birth_last.setFlow(QtWidgets.QListView.Flow.TopToBottom)
        self.listWidget_birth_last.setProperty("isWrapping", False)
        self.listWidget_birth_last.setLayoutMode(QtWidgets.QListView.LayoutMode.SinglePass)
        self.listWidget_birth_last.setViewMode(QtWidgets.QListView.ViewMode.ListMode)
        self.listWidget_birth_last.setWordWrap(True)
        self.listWidget_birth_last.setObjectName("listWidget_birth_last")
        self.label_info_birth_last = QtWidgets.QLabel(self.centralwidget)
        self.label_info_birth_last.setGeometry(QtCore.QRect(333, 160, 239, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_info_birth_last.setFont(font)
        self.label_info_birth_last.setStyleSheet("color: #FFD700;")
        self.label_info_birth_last.setText("")
        self.label_info_birth_last.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_info_birth_last.setWordWrap(True)
        self.label_info_birth_last.setObjectName("label_info_birth_last")
        self.listWidget_birth_future = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_birth_future.setGeometry(QtCore.QRect(332, 430, 241, 61))
        self.listWidget_birth_future.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.listWidget_birth_future.setMidLineWidth(1)
        self.listWidget_birth_future.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.listWidget_birth_future.setProperty("showDropIndicator", False)
        self.listWidget_birth_future.setAlternatingRowColors(False)
        self.listWidget_birth_future.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.listWidget_birth_future.setFlow(QtWidgets.QListView.Flow.TopToBottom)
        self.listWidget_birth_future.setProperty("isWrapping", False)
        self.listWidget_birth_future.setLayoutMode(QtWidgets.QListView.LayoutMode.SinglePass)
        self.listWidget_birth_future.setViewMode(QtWidgets.QListView.ViewMode.ListMode)
        self.listWidget_birth_future.setWordWrap(True)
        self.listWidget_birth_future.setObjectName("listWidget_birth_future")
        self.label_info_birth_future = QtWidgets.QLabel(self.centralwidget)
        self.label_info_birth_future.setGeometry(QtCore.QRect(333, 390, 239, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_info_birth_future.setFont(font)
        self.label_info_birth_future.setStyleSheet("color: #FFD700;")
        self.label_info_birth_future.setText("")
        self.label_info_birth_future.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_info_birth_future.setWordWrap(True)
        self.label_info_birth_future.setObjectName("label_info_birth_future")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Birthday reminder"))
        self.groupBox.setTitle(_translate("MainWindow", "Шлях до файлу"))
        self.line_path.setPlaceholderText(_translate("MainWindow", "Шлях..."))
        self.pushButton_clear.setText(_translate("MainWindow", "Очистити"))
        self.pushButton_path_file.setText(_translate("MainWindow", "..."))
        self.pushButton_FAQ_path.setText(_translate("MainWindow", "?"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Дії з даними"))
        self.pushButton_create_file.setText(_translate("MainWindow", "Створити дані"))
        self.pushButton_update_file.setText(_translate("MainWindow", "Змінити дані"))
        self.listWidget_birth_now.setSortingEnabled(True)
        self.groupBox_3.setTitle(_translate("MainWindow", "Таймер до закриття додатку"))
        self.label.setText(_translate("MainWindow", "До закриття додатку залишилось:"))
        self.pushButton_stop_timer.setText(_translate("MainWindow", "Зупинити закриття"))
        self.pushButton_exit.setText(_translate("MainWindow", "Вихід"))
        self.pushButton_setting.setText(_translate("MainWindow", "Налаштування"))
        self.listWidget_birth_last.setSortingEnabled(True)
        self.listWidget_birth_future.setSortingEnabled(True)
