# Form implementation generated from reading ui file 'd:\Проги python\Напоминание о ДР\GUI\Setting.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(416, 92)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\Проги python\\Напоминание о ДР\\GUI\\../Icons/settings.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color: #1E1E1E;\n"
"}\n"
"QPushButton{\n"
"    background-color: black;\n"
"    color: yellow;\n"
"    border: 1px solid #483D8B;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px dashed #00FA9A;\n"
"    color: #00FA9A;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #2F4F4F;\n"
"    color: #FF0000;\n"
"    border: 1px dashed #000080;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: black;\n"
"    color: #800000;\n"
"    border: none;\n"
"}\n"
"\n"
"QCheckBox{\n"
"    color:#FF4500;\n"
"}\n"
"QCheckBox:hover{\n"
"    color: #00FF00;\n"
"    border: 1px dashed #00FF00;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 25px;\n"
"    height: 25px;\n"
"    background-color: gray;\n"
"    border-radius: 10px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: white white black black;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background-color: qradialgradient(spread:pad, \n"
"                            cx:0.5,\n"
"                            cy:0.5,\n"
"                            radius:0.9,\n"
"                            fx:0.5,\n"
"                            fy:0.5,\n"
"                            stop:0 rgba(0, 255, 0, 255), \n"
"                            stop:1 rgba(0, 64, 0, 255));\n"
"}\n"
"QCheckBox:checked, QCheckBox::indicator:checked {\n"
"    border-color: black black white white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(352, 59, 59, 28))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 60, 229, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setCheckable(True)
        self.checkBox_2.setChecked(False)
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.pushButton_FAQ_check_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_FAQ_check_1.setGeometry(QtCore.QRect(300, 10, 38, 26))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_FAQ_check_1.setFont(font)
        self.pushButton_FAQ_check_1.setStyleSheet("")
        self.pushButton_FAQ_check_1.setObjectName("pushButton_FAQ_check_1")
        self.pushButton_FAQ_check_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_FAQ_check_2.setGeometry(QtCore.QRect(300, 60, 38, 26))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_FAQ_check_2.setFont(font)
        self.pushButton_FAQ_check_2.setStyleSheet("")
        self.pushButton_FAQ_check_2.setObjectName("pushButton_FAQ_check_2")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(10, 10, 275, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setCheckable(True)
        self.checkBox.setChecked(False)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Setting"))
        self.pushButton_exit.setText(_translate("MainWindow", "Зберегти"))
        self.checkBox_2.setText(_translate("MainWindow", "Після запуску згорнути додаток"))
        self.pushButton_FAQ_check_1.setText(_translate("MainWindow", "?"))
        self.pushButton_FAQ_check_2.setText(_translate("MainWindow", "?"))
        self.checkBox.setText(_translate("MainWindow", "Додати до автозавантаження Windows"))
