# Form implementation generated from reading ui file 'Setting.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(416, 269)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Icons/settings.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color: #1E1E1E;\n"
"}\n"
"QPushButton{\n"
"    background-color: black;\n"
"    color: yellow;\n"
"    border: 1px solid #483D8B;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px dashed #00FA9A;\n"
"    color: #00FA9A;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #2F4F4F;\n"
"    color: #FF0000;\n"
"    border: 1px dashed #000080;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: black;\n"
"    color: #800000;\n"
"    border: none;\n"
"}\n"
"\n"
"QCheckBox{\n"
"    color:#FF4500;\n"
"}\n"
"QCheckBox:hover{\n"
"    color: #00FF00;\n"
"    border: 1px dashed #00FF00;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 25px;\n"
"    height: 25px;\n"
"    background-color: gray;\n"
"    border-radius: 10px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: white white black black;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background-color: qradialgradient(spread:pad, \n"
"                            cx:0.5,\n"
"                            cy:0.5,\n"
"                            radius:0.9,\n"
"                            fx:0.5,\n"
"                            fy:0.5,\n"
"                            stop:0 rgba(0, 255, 0, 255), \n"
"                            stop:1 rgba(0, 64, 0, 255));\n"
"}\n"
"QCheckBox:checked, QCheckBox::indicator:checked {\n"
"     border-color: black black white white;\n"
"}\n"
"\n"
"QSpinBox {\n"
"      background: #474747;\n"
"      color: yellow;\n"
"      border: 1px dashed #00FFFF;\n"
"}\n"
"\n"
"QLabel{\n"
"    color:#FF4500;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(352, 234, 59, 28))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.checkBox_collapse_window = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_collapse_window.setGeometry(QtCore.QRect(10, 60, 229, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_collapse_window.setFont(font)
        self.checkBox_collapse_window.setCheckable(True)
        self.checkBox_collapse_window.setChecked(False)
        self.checkBox_collapse_window.setTristate(False)
        self.checkBox_collapse_window.setObjectName("checkBox_collapse_window")
        self.pushButton_FAQ_autorun = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_FAQ_autorun.setGeometry(QtCore.QRect(300, 10, 38, 26))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_FAQ_autorun.setFont(font)
        self.pushButton_FAQ_autorun.setStyleSheet("")
        self.pushButton_FAQ_autorun.setObjectName("pushButton_FAQ_autorun")
        self.pushButton_FAQ_collapse_window = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_FAQ_collapse_window.setGeometry(QtCore.QRect(300, 60, 38, 26))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_FAQ_collapse_window.setFont(font)
        self.pushButton_FAQ_collapse_window.setStyleSheet("")
        self.pushButton_FAQ_collapse_window.setObjectName("pushButton_FAQ_collapse_window")
        self.checkBox_autorun = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_autorun.setGeometry(QtCore.QRect(10, 10, 275, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_autorun.setFont(font)
        self.checkBox_autorun.setCheckable(True)
        self.checkBox_autorun.setChecked(False)
        self.checkBox_autorun.setTristate(False)
        self.checkBox_autorun.setObjectName("checkBox_autorun")
        self.pushButton_FAQ_list_birth_future = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_FAQ_list_birth_future.setGeometry(QtCore.QRect(300, 160, 38, 26))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_FAQ_list_birth_future.setFont(font)
        self.pushButton_FAQ_list_birth_future.setStyleSheet("")
        self.pushButton_FAQ_list_birth_future.setObjectName("pushButton_FAQ_list_birth_future")
        self.pushButton_FAQ_list_birth_last = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_FAQ_list_birth_last.setGeometry(QtCore.QRect(300, 110, 38, 26))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_FAQ_list_birth_last.setFont(font)
        self.pushButton_FAQ_list_birth_last.setStyleSheet("")
        self.pushButton_FAQ_list_birth_last.setObjectName("pushButton_FAQ_list_birth_last")
        self.checkBox_list_birth_future = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_list_birth_future.setGeometry(QtCore.QRect(10, 160, 281, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_list_birth_future.setFont(font)
        self.checkBox_list_birth_future.setCheckable(True)
        self.checkBox_list_birth_future.setChecked(False)
        self.checkBox_list_birth_future.setTristate(False)
        self.checkBox_list_birth_future.setObjectName("checkBox_list_birth_future")
        self.checkBox_list_birth_last = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_list_birth_last.setGeometry(QtCore.QRect(10, 110, 275, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_list_birth_last.setFont(font)
        self.checkBox_list_birth_last.setCheckable(True)
        self.checkBox_list_birth_last.setChecked(False)
        self.checkBox_list_birth_last.setTristate(False)
        self.checkBox_list_birth_last.setObjectName("checkBox_list_birth_last")
        self.spinBox_minutes = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_minutes.setGeometry(QtCore.QRect(16, 234, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBox_minutes.setFont(font)
        self.spinBox_minutes.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spinBox_minutes.setMaximum(100000)
        self.spinBox_minutes.setProperty("value", 2)
        self.spinBox_minutes.setObjectName("spinBox_minutes")
        self.spinBox_seconds = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_seconds.setGeometry(QtCore.QRect(108, 234, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBox_seconds.setFont(font)
        self.spinBox_seconds.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spinBox_seconds.setMaximum(59)
        self.spinBox_seconds.setObjectName("spinBox_seconds")
        self.label_min = QtWidgets.QLabel(self.centralwidget)
        self.label_min.setGeometry(QtCore.QRect(16, 201, 67, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_min.setFont(font)
        self.label_min.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_min.setObjectName("label_min")
        self.label_sec = QtWidgets.QLabel(self.centralwidget)
        self.label_sec.setGeometry(QtCore.QRect(110, 201, 67, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_sec.setFont(font)
        self.label_sec.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_sec.setObjectName("label_sec")
        self.pushButton_FAQ_timer = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_FAQ_timer.setGeometry(QtCore.QRect(301, 234, 38, 26))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_FAQ_timer.setFont(font)
        self.pushButton_FAQ_timer.setStyleSheet("")
        self.pushButton_FAQ_timer.setObjectName("pushButton_FAQ_timer")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Setting"))
        self.pushButton_exit.setText(_translate("MainWindow", "Зберегти"))
        self.checkBox_collapse_window.setText(_translate("MainWindow", "Після запуску згорнути додаток"))
        self.pushButton_FAQ_autorun.setText(_translate("MainWindow", "?"))
        self.pushButton_FAQ_collapse_window.setText(_translate("MainWindow", "?"))
        self.checkBox_autorun.setText(_translate("MainWindow", "Додати до автозавантаження Windows"))
        self.pushButton_FAQ_list_birth_future.setText(_translate("MainWindow", "?"))
        self.pushButton_FAQ_list_birth_last.setText(_translate("MainWindow", "?"))
        self.checkBox_list_birth_future.setText(_translate("MainWindow", "Інформація про майбутні дні народження"))
        self.checkBox_list_birth_last.setText(_translate("MainWindow", "Інформація про минулі дні народження"))
        self.label_min.setText(_translate("MainWindow", "Хвилини"))
        self.label_sec.setText(_translate("MainWindow", "Секунди"))
        self.pushButton_FAQ_timer.setText(_translate("MainWindow", "?"))
